### ISSUE TITLE
Install Nginx as a reverse proxy in front of Apache and other webservices

### ISSUE THREAD

**Issue by n-peugnet** [club-1/hosting#10]
Because Apache is slow.

### Todo

- [x] Convert Letsencrypt certificates to wildcard ones using DNS ACME challenges (this way no need to transfer each subdomain to Nginx):
  - [x] club1.fr
  - [x] 246.eu
  - [x] w-cms.top
  - [x] ecolesadefendre.fr
  - [x] roulette-russe.fr
- [x] Create a first site that redirects everything to Apache (really basic reverse proxy).
- [x] Add exceptions for each app subdomains:
  - [x] matrix
  - [x] riot.club1.fr
  - [x] jf
  - [x] dashboard
- [ ] #50
- [ ] ~~Write an article~~

**Comment by n-peugnet** [comment]
Closing this as most of it is done. The rest will be tracked in #50.
