### ISSUE TITLE
IPv6 checklist

### ISSUE THREAD

**Issue by n-peugnet** [club-1/hosting#32]
- [x] Assign static IP
- [x] Update Firewall
- [x] Write an article
- [ ] Update DNS
  - [x] club1.fr
    - [ ] subdomains
  - [ ] w-cms.top
  - [ ] 246.eu
  - [ ] ecolesadefendre.fr
  - [ ] roulette-russe.fr
- [ ] Private FTP
  - [ ] Add one more static IP
  - [ ] Choose subdomain (`ftp.club1.fr` ?)
  - [ ] Setup proftpd...
- [ ] Update bind scripts
