### ISSUE TITLE
Hosting git repos

### ISSUE THREAD

**Issue by n-peugnet** [club-1/hosting#37]
### Rationale

As for all of CLUB1 services, git repository hosting should be integrated with the user's home

#### What we don't want :

- **Gitlab** (even with ldap): it's far too heavy for what it's worth and having the possibility to share repos between a small quantity of users is not really usefull. Also repositories are stored in an obscure directory under `/var`.
- **gitolite**: it forces the users to have a key to use the service.

#### What we want:

- SSH can already be used to store a repository with write access inside a user's home directory. So let's use this.
- Repositories stored under the `/home/<user>/public/git` directory should be made accessible in read-only mode over http at `club1.fr/~<user>/git/`.
- A **_simple_** web ui should also be accessible at this same address (gitweb or cgit style).

With these two differentiated accesses (on read-write and one read-only) it is possible to use git in multi-user based on the original distributed workflow for which git has been built:

- each user has it's own public repository with a read-only access
- each user can the pull from each others repository to merge their work

### ToDo

- [x] HTTP git backend access
- [x] Choose the WebUI and install it (probably using apache with it's CGI module)
- [ ] Add docs on how to init and use a repository on CLUB1 club-1/docs#10

### Links

- https://www.isi.edu/~calvin/gitweb.htm
- https://git-scm.com/book/pl/v2/Git-on-the-Server-Smart-HTTP
- https://git-scm.com/book/pl/v2/Git-on-the-Server-GitWeb
